title: Kinsale Green Printing
description: >- # this means to ignore newlines until "baseurl:"
  You can find how to print economically in Word, Excel, PDF and Powerpoint on this site.
url: "https://mickadoo.github.io/greenprint"

theme: minima